Data_Collection/CRON_scripts/foph.sh, Data_Collection/CRON_scripts/foph_fetch.py, playbooks/crontab.yml
=> Foph fetch

Data_Collection/CRON_scripts/get_data.py, Data_Collection/CRON_scripts/make_forecast.py
it was a minor thing, that somehow escaped from your testing @eduardocorrearaujo .
=> Make forecast bugfix

Data_Collection/CRON_scripts/colombia_data.py
Reverts thegraphnetwork/EpiGraphHub#41
=> Revert "Get colombia data"

playbooks/crontab.yml
to ansible crontab playbook and executed it. closes issue #43
=> Added colombia downloading

docker/public_welcome.html
This PR starts the necessary code for the automatic patching of the landing page.
=> Landing page template patching 

ansible/playbooks/local.yml
This PR aims to fix this problem: https://github.com/thegraphnetwork/EpiGraphHub/runs/5411131593?check_suite_focus=true#step:8:47
=> chore(ansible): Create a .ssh folder

Data_Collection/CRON_scripts/colombia_data.py, Data_Collection/CRON_scripts/foph_fetch.py, Documentation/instruction_name_tables.md
I made some corrections to put all the column names in the lower case and the name in the format combined for the foph datasets and the Colombia dataset. As soon as the PR is approved, I will also change the names in the tables into the database.
=> Correct foph name

Data_Collection/CRON_scripts/colombia_data.py
Solved #40. 
I added a loop for to apply the method `.strip()` in all the string columns of the data frame. This method removes any space in the start and end of a string. 
Before I open the PR I ran the code to all the data to change the strings that already were in the database.
=> Correct bug in colombia_data.py

Data_Collection/CRON_scripts/make_forecast.py
added loggin to catch exceptions
=> fixed broken lines in make_forecast

Documentation/instruction_name_tables.md
This PR was created to solve issue #44.
In the .md there are instructions about how the tables should be named in the epigraphhub.
=> Create documentation to name the tables

conda/prod.yaml
=> chore(deps): Add gsheetsdb

docker/superset/superset_config.py
I think this is all it takes, But I could not test. @xmnlab could you test it and see if it works?
=> Added support to translations

docker/superset/superset_config.py
Added a bunch of new language translations!
=> added more languages

docker/superset/public_welcome.html
@xmnlab Let's test this on the staging server. Do you think we should add a recaptcha to registration?
=> 86 update welcome page

Makefile, ansible/playbooks/git.yml, ansible/playbooks/local.yml, ansible/playbooks/superset.yml, docker/compose-prod.yaml
This PR aims to fix and improve the ansible playbooks
=> fix(ansible): Fix ansible playbooks

ansible/playbooks/local.yml
This PR aims to fix some issues about the ssh connection from the ansible command
=> fix(ansible): Fix local playbook

.gitignore, README.md, docker/superset/public_welcome.html
=> Add Discord references

Makefile, conda/superset.yaml, containers/airflow/dags/foph_dag.py, containers/airflow/dags/owid_dag.py, containers/healthcheck.sh, containers/superset/entrypoint.sh
This PR aims to use a specific version and build number for superset
=> Fix superset static image folder access

.github/workflows/main.yaml, Documentation/dataanalysis.md, conda/airflow.yaml, containers/airflow/dags/colombia_dag.py, containers/airflow/dags/foph_dag.py, containers/airflow/dags/owid_dag.py, containers/compose-base.yaml, containers/postgresql/sql/dev/02-epigraphhub.sql
Refactor:
depends on https://github.com/thegraphnetwork/epigraphhub_py/pull/193
=> chore(refactor): Refactor of Data Collection modules to match ETL workflow

conda/superset.yaml, containers/superset/Dockerfile
=> chore(dep): Add libecpg

containers/airflow/dags/brasil/sinan.py, containers/airflow/dags/brasil/sinan_drop_table.py
=> fix(sinan-dag): remove get_parsing_context import

containers/airflow/dags/switzerland/foph_dag.py, containers/airflow/dags/switzerland/foph_metadata_dag.py, containers/airflow/dags/switzerland/foph_weekly_dag.py
fix #184 
new/updatable tables:
```
switzerland.foph_cases_byage_w                              switzerland.foph_deathbreakthroughvaccpersons_byage_w_meta  switzerland.foph_hospreason_byage_w
switzerland.foph_cases_byage_w_meta                         switzerland.foph_deathreason_byage_w                        switzerland.foph_hospreason_byage_w_meta
switzerland.foph_cases_bysex_w                              switzerland.foph_deathreason_byage_w_meta                   switzerland.foph_hospvaccpersons_byage_w
switzerland.foph_cases_bysex_w_meta                         switzerland.foph_deathvaccpersons_byage_w                   switzerland.foph_hospvaccpersons_byage_w_meta
switzerland.foph_cases_d_meta                               switzerland.foph_deathvaccpersons_byage_w_meta …
```
=> feat(foph-DAG): foph weekly DAG & foph metadata DAG
